export const SET_USER = 'SET_USER';
export const ADD_USER_FOLLOW = 'ADD_USER_FOLLOW';
export const REMOVE_USER_FOLLOW = 'REMOVE_USER_FOLLOW';
export const SET_USER_POST_IDS = 'SET_USER_POST_IDS';
export const ADD_USER_POST_ID = 'ADD_USER_POST_ID';
export const REMOVE_USER_POST_ID = 'REMOVE_USER_POST_ID';
export const SET_USER_LIKED_IDS = 'SET_USER_LIKED_IDS';