export const SET_EXPLORE_TOP_IDS = 'SET_EXPLORE_TOP_IDS';
export const SET_EXPLORE_LATEST_IDS = 'SET_EXPLORE_LATEST_IDS';
export const SET_EXPLORE_FILTER = 'SET_EXPLORE_FILTER';
export const SET_EXPLORE_FILTER_REACHED_END = 'SET_EXPLORE_FILTER_REACHED_END';