name: app

on:
  pull_request:
    branches: [ main ]

jobs:
  pull_request:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - run: cd ./frontend
        - run: npm ci
        - run: npm run build
